language: python
python:
  - "2.7"

# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  coverage run -m unittest discover --start-directory tests --pattern *_test.py

after_success:
  coveralls
